[mozci]
data_sources = ["treeherder_client", "hgmo", "taskcluster", "errorsummary"]

[mozci.cache]
retention = 40320
serializer = "compressedpickle"

[mozci.cache.stores]
s3 = { driver = "s3", bucket = "communitytc-bugbug", prefix = "data/adr_cache/" }
