name: mlops-metaflow-1
channels:
  - conda-forge
dependencies:
  # This is the base environment to deploy metaflow
  - python=3.10
  - amqp=5.1.1
  - beautifulsoup4=4.12.2
  - boto3=1.28.12
  - google-auth=2.22.0
  - google-cloud-storage=2.10.0
  - imbalanced-learn=0.11.0
  - kubernetes
  - lmdb
  - markdown2=2.4.10
  - matplotlib=3.7.2
  - mercurial
  - metaflow=2.9.11
  - notebook=7.0.1
  - numpy=1.22.4
  - orjson=3.9.2
  - pandas=2.0.3
  - plotly=5.15.0
  - psutil=5.9.5
  - pyOpenSSL>=0.14  # Could not find a version that satisfies the requirement pyOpenSSL>=0.14; extra == "security" (from requests[security]>=2.7.0->libmozdata==0.1.43)
  - python-dateutil=2.8.2
  - ratelimit=2.2.1
  - requests=2.31.0
  - scikit-learn=1.1.3
  - scipy=1.11.1
  - sendgrid
  - shap[plots]=0.42.1
  - tabulate=0.9.0
  - tenacity=8.2.2
  - tqdm=4.65.0
  - xgboost=1.7.6
  - zstandard
  - setuptools~=68.0.0
